apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/dev/*
build:
  local:
    push: true
  artifacts:
    - image: ragrag/insta-post-service
      context: post-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: '.env'
            dest: .
          - src: 'swagger.yaml'
            dest: .