tags:
- name: Authentication
  description: User Authentication

host: http://localhost:3005
basePath: /api/v1
schemes:
 - https
 - http

paths:
# [POST] /api/v1/signup
  /api/v1/signup:
    post:
      tags:
      - Authentication
      summary: Registration
      parameters:
      - name: body
        in: body
        description: User Registration
        required: true
        schema:
          type: object
          properties:
            email:
              type: string
              description: user email
            username:
              type: string
              description: username
            password:
              type: string
              description: user password
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        401:
          description: 'Unauthorized'
        409:
          description: 'Conflict'

  /api/v1/login:
    post:
      tags:
      - Authentication
      summary: Login
      parameters:
      - name: body
        in: body
        description: User Login
        required: true
        schema:
          type: object
          properties:
            email:
              type: string
              description: user email
            password:
              type: string
              description: user password
      responses:
        200:
          description: 'Success'
        400:
          description: 'Bad Request'
        404:
          description: 'Not Found'


# definitions
definitions:
  user:
    type: object
    required:
        - email
        - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
        

