kind: Deployment
apiVersion: apps/v1
metadata:
  name: users-dev-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users 
    spec:
      containers:
        - name: users
          image: ragrag/insta-user-service
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    name: users
spec:
  selector:
    app: users
  type: ClusterIP
  ports:
    - port: 3005
      name: users
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: users-service-np
  labels:
    name: users
spec:
  selector:
    app: users
  type: NodePort
  ports:
    - port: 3005
      nodePort: 30005
      name: users
      protocol: TCP
